version: '2'
services:

  rundeckwebservice:
    restart: always
    image: rundeck/rundeck:3.2.5
    container_name: rundeckwebservice
    ports:
      - 4440:4440
    environment:
 
    links:
      - mariadbrundeck
    depends_on:
      - mariadbrundeck
    volumes:
      - ./data/projects:/var/rundeck/projects:rw
      - ./data/keys:/var/lib/rundeck_ssh:ro
    networks:
      - rundeck-mariadb-network  

  mariadbrundeck:
    restart: always
    image: mariadb:5.5.54
    container_name: mariadbrundeck
    command: mysqld --innodb-buffer-pool-size=20M
    environment:
      - MYSQL_ROOT_PASSWORD=R00t@rUnd3ck@RunRecK
      - MYSQL_DATABASE=rundeck
      - MYSQL_USER=rundeck
      - MYSQL_PASSWORD=Us3r@rUnd3ck@RunRecK
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    expose:
      - 3306
    networks:
      - rundeck-mariadb-network  
  
  phpmyadminrundeck:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadminrundeck
    restart: always
    ports:
      - 0.0.0.0:8181:80
    links:
      - mariadbrundeck
    environment:
      - PMA_HOST=mariadbrundeck
    networks:
      - rundeck-mariadb-network

networks:
  rundeck-mariadb-network:
    driver: bridge